# Generated by Django 4.2.6 on 2023-10-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_price_producttype_alter_product_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updateDate',
            field=models.DateField(auto_now=True),
        ),
    ]
