# Generated by Django 4.2.6 on 2023-10-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
